### ISSUE TITLE
Buffer size insufficient

### ISSUE THREAD

**Issue by fmedv** [fmedv/docker-go-ipfs#2]
**Describe the bug**
When the host starts a warning message appeared saying:
> Creating network "ipfs_ipfs" with driver "bridge"
Creating ipfs_app ... done
Attaching to ipfs_app
app_1  | Changing user to ipfs
app_1  | ipfs version 0.8.0
app_1  | Found IPFS fs-repo at /data/ipfs
app_1  | go-ipfs version: 0.8.0-ce693d7
app_1  | Repo version: 11
app_1  | System version: amd64/linux
app_1  | Golang version: go1.14.4
**app_1  | 2021/04/18 01:51:12 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.**
app_1  | Swarm listening on /ip4/127.0.0.1/tcp/4001
app_1  | Swarm listening on /ip4/127.0.0.1/udp/4001/quic
app_1  | Swarm listening on /ip4/172.23.0.2/tcp/4001
app_1  | Swarm listening on /ip4/172.23.0.2/udp/4001/quic
app_1  | Swarm listening on /p2p-circuit
app_1  | Swarm announcing /ip4/127.0.0.1/tcp/4001
app_1  | Swarm announcing /ip4/127.0.0.1/udp/4001/quic
app_1  | Swarm announcing /ip4/84.115.220.57/udp/32405/quic
app_1  | API server listening on /ip4/0.0.0.0/tcp/5001
app_1  | WebUI: http://0.0.0.0:5001/webui
app_1  | Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8080
app_1  | Daemon is ready

**To Reproduce**
1. Start Docker container

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - [ ] Native Linux
 - [x] WSL
 - WSL Version: 2
 - Docker Engine Version: 20.10.5

**Comment by Aminechakr** [comment]
any feedback on this issue ?

**Comment by fmedv** [comment]
You'd have to increase network buffer size either with command `sysctl -w net.core.rmem_max=2500000` (non-BSD) or `sysctl -w kern.ipc.maxsockbuf=3014656` (BSD) as stated in https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size.
